### ISSUE TITLE
annotateDiffrepot bug - incoherence between ids when RT are in minute

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/camera#12]
OTRS - 2016112910000118
Si on opte pour RT en minutes et qu'on veut utiliser le annotateDiffreport en tant que
variableMetadata pour faire une filtration ou qualityMetrix, ca plante car
l'identificateur d'ions est resté en seconde et du coup, il n'y a pas coh?rence entre les
fichiers dataMatrix et variablesMetadata.
Merci de votre attention
JF

ping @jfrancoismartin @fgiacomoni

**Comment by lecorguille** [comment]
@jfrancoismartin I can't manage to reproduce the bug. Can you share me a history with dataset until qualityMatrix?

**Comment by yguitton** [comment]
The xcms:::groupnames function can be an easy solution. With a test like:
if variableMetadata[,"names"]!=dataMatrix[,"name"] then try( xcms:::groupnames( here have to load the right xset object and fill mzdec and rtdec with the same parameters entered by user before))

or something with an adaptation from that groupnames function

**Comment by jfrancoismartin** [comment]
@lecorguille @yguitton 
I wrote an OTRS ticket with an example of this bug and share 
https://galaxy.workflow4metabolomics.org/u/jfmartin-1/h/imported-sacuri-light-w4e-2016-extraction

**Comment by lecorguille** [comment]
Done : https://github.com/workflow4metabolomics/camera/pull/17

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by jfrancoismartin** [comment]
@lecorguille @yguitton
Salut,
I checked the new "namecustom", it seems to work. I could run an univariate test with the result of diffreport without the problem I had before. Just a strange effect, see the example below 
defaultname    namecustom
M187T379_1	M186.73T6.3_1
M187T379_2	M186.82T6.3_2
M187T379_3	M186.9T6.3_3
M187T379_4	M187.28T6.3_4
In the first column, the default name with the extensons _1 _2 etc because they are duplicated. In the second column the custom names with 2 decimals for m/z. With the 2 decimals they are no more duplicated but still have the extension _1 _2 . I can't say if it could be a problem...
I also checked again the inhouse CAMERA adduct files and it works with a csv file with comma separated columns (it doesn't work with ";")

**Comment by lecorguille** [comment]
@jfrancoismartin Great!
And indeed, I kept the _1 and _2 to keep a kind of safety linage between the `name` and the `namecustom` and to be **really** sur that there is no duplicates. I thought about adding a checking before adding those _1 but I'm was lazy at that moment.
If it's a problem, let me know, I can easly change this behaviour.

**Comment by jfrancoismartin** [comment]
At least, we can be sure that there is no duplicated id...

**Comment by lecorguille** [comment]
- [X]  validated by @jfrancoismartin
