### ISSUE TITLE
Add section in the tool form

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/camera#25]
> This tag is used to group parameters into sections of the interface. Sections are implemented to replace the commonly used tactic of hiding advanced options behind a conditional, with sections you can easily visually group a related set of options. 
> 
> https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#A.3Csection.3E_tag_set

**Comment by lecorguille** [comment]
@workflow4metabolomics/ms 
Can you look at the new version of camera.annotate on galaxydev?

I add some sections to separate the parameters according to their functions.
Is it clearer? Useful? Useless?

Note that I guess that the rerun will fail because of those sections. So we will have to check the existing workflow.

**Comment by jfrancoismartin** [comment]
Good ! easier to use but I would have organised the different blocs of parameters differently and with real names instead of R functions names. 
1st Bloc : Grouping co-eluted peaks
- groupFWHM and GroupCorr and general
2nd Bloc : "Isotopes and Adducts annotation"
- findIsotopes findAdducts
3rd Bloc : "Statistics and results export"
- diffreport and export options

But Yann the Boss must agree with that...
JF

**Comment by lecorguille** [comment]
I like the idea to display real name. I was also thinking about that. In my point of view, displaying both is important. 
About the grouping, I don't know. If those function have been splited, it should be because they have different purposes. 
More review please :)

**Comment by melpetera** [comment]
I simply LOVE this section thing! 

About the section names, I agree with the real names thing, but I find it complicated mergng sections since groupCorr and findAdducts are only used when wanting the "quick" version - I think it's confusing merging it with the mandatory groupFWHM and findIsotopes.  Would it be ok to keep the section as they are now but replacing "Function:" by the real names suggested by @jfrancoismartin ?
It would look like this:
Grouping co-eluted peaks: groupFWHM
Isotopes annotation: findIsotopes
Grouping co-eluted peaks: General
Adducts annotation: findAdducts
Grouping co-eluted peaks: groupCorr
Statistics and results export: diffreport
Statistics and results export: export options

What do you think about it?

**Comment by lecorguille** [comment]
Do you have a more explicite Real names for the different methods?
According to this [pdf](https://bioconductor.org/packages/3.4/bioc/vignettes/CAMERA/inst/doc/CAMERA.pdf), I propose this: 

- Group co-eluted peaks based on RT [groupFWHM]
- Annotate Isotopes [findIsotopes]
- Grouping co-eluted peaks: General
- Verifying grouping co-eluted peaks [groupCorr]
- Annotate Adducts [findAdducts]
- Statistics and results export: [diffreport]
- Results export options

I also reordered the steps.

About the General options, can you say that?
- `ppm` and `mzabs` are used by `findIsotopes` and `findAdducts` ([source](https://github.com/sneumann/CAMERA/blob/118bfb996f8f56bf10fc0bcf91d2d4a8930faa65/R/xsAnnotate.R#L1383)). So group them in a section called `Annotate general options`
- `max_peaks` is only used by `findAdducts` ([source](https://github.com/sneumann/CAMERA/blob/118bfb996f8f56bf10fc0bcf91d2d4a8930faa65/R/xsAnnotate.R#L1395)). So move it in `Adducts annotation: findAdducts`

2nd proposition:
- Group co-eluted peaks based on RT [groupFWHM]
- Annotate Isotopes [findIsotopes]
- Annotate (general options)
- Verifying grouping co-eluted peaks [groupCorr]
- Annotate Adducts [findAdducts]
- Statistics and results export: [diffreport]
- Results export options

**Comment by melpetera** [comment]
The 2nd proposition seems ok. I would just switch order for "Annotate Isotopes [findIsotopes]" and "Annotate (general options)", and maybe rename the second one "Annotation general options". 

What do you think of it @jfrancoismartin ? @yguitton ?

**Comment by melpetera** [comment]
Bug with the "quick" option: clicking on Execute generates a pop up
`Job submission failed`
`Error executing tool: cannot find 'findadducts' while searching for 'quick_block.findadducts.polarity'`

**Comment by lecorguille** [comment]
Fix: https://github.com/workflow4metabolomics/camera/pull/28
I plan to update the dev instance with my last proposition of sections.

**Comment by lecorguille** [comment]
Pass2: https://github.com/workflow4metabolomics/camera/pull/29/commits/b54181234af86cad66151502df8fe63fb7f99b20

**Comment by lecorguille** [comment]
- [x]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by melpetera** [comment]
The quick option works. But now it is the "positive/negative" in Rdata output file when not using the quick option that has a problem: the output name is always "annotate.quick.Rdata" even without using Quick. Previously it was for example "annotate.positive.Rdata".

**Comment by lecorguille** [comment]
Fix: https://github.com/workflow4metabolomics/camera/pull/31
Try again :)

**Comment by melpetera** [comment]
Ok, names are right! Validated.

**Comment by lecorguille** [comment]
Cool

**Comment by lecorguille** [comment]
Thanks Mélanie and Jean-François
